# This file was generated by GoReleaser. DO NOT EDIT.
cask "acr" do
  name "acr"
  desc "Agentic Code Reviewer - run parallel code reviews with AI agents"
  homepage "https://github.com/richhaase/agentic-code-reviewer"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acr"

  on_macos do
    on_intel do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Darwin_x86_64.tar.gz"
      sha256 "08ec95b5b4c1c0f1649d6ff47345928d412313fcf34d0586c481809ac7bf62aa"
    end
    on_arm do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Darwin_arm64.tar.gz"
      sha256 "046a034814b31c8c3cf87386e8fbc2e89a6e1b3fb21a1bb6dd2ff9a4ec651d54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Linux_x86_64.tar.gz"
      sha256 "62e980220c7edda03691f615cdb3f96c2e9c9609448fe2e3797f368dfad5a84b"
    end
    on_arm do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Linux_arm64.tar.gz"
      sha256 "44770fabadea272d08c867f3faf00a16bc8c05b70c4637f11001fcbcca1e4708"
    end
  end

  caveats do
    "ACR has been installed! Get started with:"
    "  acr --help"
    "  acr --reviewers 5 --base main"
    ""
    "Documentation: https://github.com/richhaase/agentic-code-reviewer#readme"
    ""
    "ACR runs parallel code reviews using AI agents and summarizes findings."
    "It requires the 'codex' CLI to be installed."
  end

  # No zap stanza required
end
