# This file was generated by GoReleaser. DO NOT EDIT.
cask "acr" do
  name "acr"
  desc "Agentic Code Reviewer - run parallel code reviews with AI agents"
  homepage "https://github.com/richhaase/agentic-code-reviewer"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acr"

  on_macos do
    on_intel do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Darwin_x86_64.tar.gz"
      sha256 "4459ca842d7ff544fff0d8acba1af41047f2f753f64c54c3f3b25d3d3219d940"
    end
    on_arm do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Darwin_arm64.tar.gz"
      sha256 "03a65971a71509041b48efce882926f24ebed360235dd583c8ecbdb16f5d9ee3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Linux_x86_64.tar.gz"
      sha256 "07c5c9d2ca2611f52cb3eb89a046f91ffcf85c9a46d66fabaff234d6cd2a0a7c"
    end
    on_arm do
      url "https://github.com/richhaase/agentic-code-reviewer/releases/download/v#{version}/agentic-code-reviewer_#{version}_Linux_arm64.tar.gz"
      sha256 "e452e5d2ee5ada08702078396c9ef23ec156126395934b475ae3a3231df096d6"
    end
  end

  caveats do
    "ACR has been installed! Get started with:"
    "  acr --help"
    "  acr --reviewers 5 --base main"
    ""
    "Documentation: https://github.com/richhaase/agentic-code-reviewer#readme"
    ""
    "ACR runs parallel code reviews using AI agents and summarizes findings."
    "It requires the 'codex' CLI to be installed."
  end

  # No zap stanza required
end
