# This file was generated by GoReleaser. DO NOT EDIT.
cask "bigboard" do
  version "0.7.2"

  on_macos do
    on_arm do
      sha256 "3c15ce4bc303bf220b5cc0f90881f2be60f38a1cd2a518004343e2810b3d98f2"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c1eb29240459c0b7da41cf1a63094e8a887fcc1aed3e0ff8b3883def8a70e6e"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c0072b0aa8c937d12f8b1bb4289cb355041e778d70ecc209023e0add2ed39f5"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ca345e905bf702812e27cc26f8ee3c7d678754f013f07a665c0007f82fd021b"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "bigboard"
  desc "Terminal dashboard for contributor activity across Git repositories"
  homepage "https://github.com/richhaase/bigboard"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "bigboard"

  # No zap stanza required
end
