# This file was generated by GoReleaser. DO NOT EDIT.
cask "bigboard" do
  version "0.11.1"

  on_macos do
    on_arm do
      sha256 "f98da09e17b0a322ae62e0d9e22e82fef806c25c0a324140c759c5bdd09cde49"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "db0a664f95a7fe3a45f8f5fa3265885c4476d3278062c58334fd7c561ea4922f"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5d7c1dd76650c468914c9df1ba49b2a2d85a0270720b0aa5cda3980e293efd82"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d33338eb92e0e0e9cdf78e3ba29edb743d4a851fe58028bd83fa9434a52f200"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "bigboard"
  desc "Terminal dashboard for contributor activity across Git repositories"
  homepage "https://github.com/richhaase/bigboard"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "bigboard"

  # No zap stanza required
end
