# This file was generated by GoReleaser. DO NOT EDIT.
cask "bigboard" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "8a10fdf3006feff94184090d39ff89b74cb058f20487c9738e99f60856b8b25e"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e47059d37a96a1f49b5fcb77c972bedee48c7d5cd0bd18ad087dc54bda0ecc01"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3df743abf0cd3d7b60041ac007ed365a73a799fd10798a604f46e3391a6a0e69"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7724828ea458136c5363cd7d948bbf1f4d57dcf3c016ca1bd89ebd0925b9a90"
      url "https://github.com/richhaase/bigboard/releases/download/v#{version}/bigboard_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "bigboard"
  desc "Terminal dashboard for contributor activity across Git repositories"
  homepage "https://github.com/richhaase/bigboard"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "bigboard"

  # No zap stanza required
end
