# This file was generated by GoReleaser. DO NOT EDIT.
cask "plonk" do
  desc "The unified package and dotfile manager for developers who tinker"
  homepage "https://github.com/richhaase/plonk"
  version "0.28.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plonk"

  on_macos do
    on_intel do
      url "https://github.com/richhaase/plonk/releases/download/v0.28.1/plonk_0.28.1_Darwin_x86_64.tar.gz"
      sha256 "de3120af44093a826e6a53dc2f09e079d14185aa6de32622b7a355bd1559ddbc"
    end
    on_arm do
      url "https://github.com/richhaase/plonk/releases/download/v0.28.1/plonk_0.28.1_Darwin_arm64.tar.gz"
      sha256 "166be4354d865857c596226bfd268617694d297b09322ed6178f41d1183fff43"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/richhaase/plonk/releases/download/v0.28.1/plonk_0.28.1_Linux_x86_64.tar.gz"
      sha256 "6e5ecf05e3e5253ce121bbf2822574f021d23a538c86564f714f0df1bad1337c"
    end
    on_arm do
      url "https://github.com/richhaase/plonk/releases/download/v0.28.1/plonk_0.28.1_Linux_arm64.tar.gz"
      sha256 "b80bb484551fa60f258185848864d5cd12bdd07736813023496df9863747db75"
    end
  end

  caveats do
    "Plonk has been installed! Get started with:"
    "  plonk --help"
    "  plonk clone <your-github-username>/dotfiles"
    ""
    "Documentation: https://github.com/richhaase/plonk#readme"
    ""
    "Plonk manages both your dotfiles and packages in one unified tool."
    "It requires Homebrew as a prerequisite."
  end

  # No zap stanza required
end
