# This file was generated by GoReleaser. DO NOT EDIT.
cask "plonk" do
  desc "The unified package and dotfile manager for developers who tinker"
  homepage "https://github.com/richhaase/plonk"
  version "0.11.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plonk"

  on_macos do
    on_intel do
      url "https://github.com/richhaase/plonk/releases/download/v0.11.6/plonk_0.11.6_Darwin_x86_64.tar.gz"
      sha256 "425a8aa0c793253a90a9be874adc7f2ecca2dc3f139bcc817a2c3d153cbd17b9"
    end
    on_arm do
      url "https://github.com/richhaase/plonk/releases/download/v0.11.6/plonk_0.11.6_Darwin_arm64.tar.gz"
      sha256 "ad21169983f36399e2373e9b469ef7157fa42220e6c28489b3d464571fc3cf46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/richhaase/plonk/releases/download/v0.11.6/plonk_0.11.6_Linux_x86_64.tar.gz"
      sha256 "7828a3f00307e38bbe67bae1c9150def842867fa73cf4f66ff466f1974e44ae3"
    end
    on_arm do
      url "https://github.com/richhaase/plonk/releases/download/v0.11.6/plonk_0.11.6_Linux_arm64.tar.gz"
      sha256 "9c3e362439c0db33000807c68d2c3f7903122b2828d06f47c98e7250deaf5703"
    end
  end

  caveats do
    "Plonk has been installed! Get started with:"
    "  plonk --help"
    "  plonk clone <your-github-username>/dotfiles"
    ""
    "Documentation: https://github.com/richhaase/plonk#readme"
    ""
    "Plonk manages both your dotfiles and packages in one unified tool."
    "It requires Homebrew as a prerequisite."
  end

  # No zap stanza required
end
