# This file was generated by GoReleaser. DO NOT EDIT.
cask "plonk" do
  desc "The unified package and dotfile manager for developers who tinker"
  homepage "https://github.com/richhaase/plonk"
  version "0.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plonk"

  on_macos do
    on_intel do
      url "https://github.com/richhaase/plonk/releases/download/v0.13.0/plonk_0.13.0_Darwin_x86_64.tar.gz"
      sha256 "dc1f7a7c881c5b3079d5739482f988d9daed36a6c424a6f99554e8c60729c893"
    end
    on_arm do
      url "https://github.com/richhaase/plonk/releases/download/v0.13.0/plonk_0.13.0_Darwin_arm64.tar.gz"
      sha256 "40358795c0a2def7190bc5a87c0cf0b0bdf006a42381b28e209f1ae194c13a42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/richhaase/plonk/releases/download/v0.13.0/plonk_0.13.0_Linux_x86_64.tar.gz"
      sha256 "b27bdc171f3867c9acf5f1cab7a4c1a9d00c962b5755f5d0eb13670bee97e377"
    end
    on_arm do
      url "https://github.com/richhaase/plonk/releases/download/v0.13.0/plonk_0.13.0_Linux_arm64.tar.gz"
      sha256 "598b501b7946bde1455ad03453eb6af485ada7c970fdcca8ef4b02fbd122d16a"
    end
  end

  caveats do
    "Plonk has been installed! Get started with:"
    "  plonk --help"
    "  plonk clone <your-github-username>/dotfiles"
    ""
    "Documentation: https://github.com/richhaase/plonk#readme"
    ""
    "Plonk manages both your dotfiles and packages in one unified tool."
    "It requires Homebrew as a prerequisite."
  end

  # No zap stanza required
end
